name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ./id_rsa
          chmod 600 ./id_rsa

      - name: Copy files to server
        run: scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_rsa ./* root@"${{ secrets.SERVER_IP }}":/root/joplin-adonis

      - name: Build and restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_rsa root@"${{ secrets.SERVER_IP }}" "
          cd /root/joplin-adonis
          npm ci
          node ace build
          cd build
          npm ci --omit=dev
          cd ..
          pm2 restart ecosystem.config.cjs || pm2 start ecosystem.config.cjs
          "
